-- Create a table for Public Profiles
create table templates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text not null,
  sub_category text not null,
  price text not null,
  tech text[] not null,
  image_url text
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table templates enable row level security;

-- Policy: Allow everyone to read templates
create policy "Public templates are viewable by everyone"
  on templates for select
  using ( true );

-- Policy: Allow only authenticated users (admins) to insert/update/delete
create policy "Admins can insert templates"
  on templates for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update templates"
  on templates for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete templates"
  on templates for delete
  using ( auth.role() = 'authenticated' );
